# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2 
  end
  
  # Network Settings
  config.vm.network "private_network", ip: "192.168.111.113"

end
